INSERT INTO `#__osmembership_configs` (`id`, `config_key`, `config_value`) VALUES
(1, 'registration_integration', '1'),
(2, 'show_login_box_on_subscribe_page', '1'),
(3, 'cb_integration', '0'),
(4, 'enable_captcha', '0'),
(5, 'enable_tax', '0'),
(6, 'enable_coupon', '0'),
(7, 'enable_cardtypes', 'Visa,MasterCard,Discover,Amex'),
(8, 'tax_rate', '10'),
(9, 'use_https', '0'),
(10, 'accept_term', '0'),
(11, 'article_id', '0'),
(12, 'date_format', 'm-d-Y'),
(13, 'currency_symbol', '$'),
(14, 'decimals', '2'),
(15, 'dec_point', '.'),
(16, 'thousands_sep', ','),
(17, 'currency_position', '0'),
(18, 'number_columns', '3'),
(19, 'default_country', 'United States'),
(20, 'from_name', ''),
(21, 'from_email', ''),
(22, 'notification_emails', ''),
(23, 'admin_email_subject', 'New subscription for [PLAN_TITLE]'),
(24, 'admin_email_body', '<p>Dear Admin</p>\r\n<p>User <strong>[FIRST_NAME] [LAST_NAME]</strong> has just subscribed for subscription plan <strong>[PLAN_TITLE]</strong>. The subscription detail is as follow:</p>\r\n<p>[SUBSCRIPTION_DETAIL] </p>\r\n<p>Regards,</p>\r\n<p>Company Name</p>'),
(25, 'user_email_subject', 'Subscription for [PLAN_TITLE] plan confirmation'),
(26, 'user_email_body', '<p>Dear <strong>[FIRST_NAME] [LAST_NAME]</strong></p>\r\n<p><strong></strong>Thanks for subscribing to our subscription plan <strong>[PLAN_TITLE]. </strong>Your subscription detail is as follow:</p>\r\n<p>[SUBSCRIPTION_DETAIL]</p>\r\n<p>Regards,</p>\r\n<p>Company Name</p>'),
(27, 'user_email_body_offline', '<p>Dear <strong>[FIRST_NAME] [LAST_NAME]</strong></p>\r\n<p><strong></strong>Thanks for subscribing to our subscription plan <strong>[PLAN_TITLE]. </strong>Your subscription detail is as follow:</p>\r\n<p>[SUBSCRIPTION_DETAIL]</p>\r\n<p>Please send the offline payment via our bank account. Information of our bank account is as follow :</p>\r\n<p>Tuan Pham Ngoc, Ngan Hang Ngoai Thuong Vietcombank, Account Number XXXYYYZZZZ</p>\r\n<p>After receiving your payment, we will activate your account and you can start access to resources on our site. If we don''t receive your payment within 3 days, we will cancel your subscription.</p>\r\n<p>Regards,</p>\r\n<p>Company Name</p>'),
(28, 'subscription_approved_email_subject', 'Your subscription for [PLAN_TITLE] approved'),
(29, 'subscription_approved_email_body', '<p>Dear <strong>[FIRST_NAME] [LAST_NAME]</strong></p>\r\n<p>Your subscription for <strong>[PLAN_TITLE]</strong> has just been approved by administrator. Your subscription detail is as follow:</p>\r\n<p>[SUBSCRIPTION_DETAIL]</p>\r\n<p>You can now login to your account to access to allowed resources on our site.</p>\r\n<p>Regards,</p>\r\n<p>Compnay Name</p>'),
(30, 'subscription_form_msg', '<p>Please enter information on the form below to process subscription for <strong>[PLAN_TITLE]</strong>. The price you have to pay is <strong>[AMOUNT]</strong>.</p>'),
(31, 'subscription_confirmation_message', '<p>Please review the subscription information for <strong>[PLAN_TITLE]</strong>. If they are correct, please click on Process button to process the subscription. If there are any information in-correct, you can click on Back button to edit it.</p>'),
(32, 'thanks_message', '<p>Thanks <strong>[FIRST_NAME] [LAST_NAME]</strong> for subscribing to <strong>[PLAN_TITLE]</strong> subscription plan. Your subscription detail is as follow:</p>\r\n<p>[SUBSCRIPTION_DETAIL]</p>\r\n<p>You can now login to your account to access to the allowed resources on our site.</p>\r\n<p>Regards,</p>\r\n<p>Company Name</p>'),
(33, 'thanks_message_offline', '<p>Thanks <strong>[FIRST_NAME] [LAST_NAME]</strong> for subscribing to <strong>[PLAN_TITLE]</strong> subscription plan. Your subscription detail is as follow:</p>\r\n<p>[SUBSCRIPTION_DETAIL]</p>\r\n<p>Please send payment to our financial department ASAP. After receiving your payment, we will activate your subscription and you can login to access to allowed resources on our site.</p>\r\n<p>Regards,</p>\r\n<p>Company Name</p>'),
(34, 'cancel_message', '<p>You cancelled your subscription.</p>'),
(35, 'failure_message', '<p>Your payment for subscribing to <strong>[PLAN_TITLE]</strong> as failure. Please see the error message below, then go back and try again.</p>'),
(36, 'subscription_renew_form_msg', '<p>Please enter information on the form below to process renew subscription for <strong>[PLAN_TITLE] </strong>for <strong>[NUMBER_DAYS] days</strong>. The price you have to pay is <strong>[AMOUNT].</strong></p>'),
(37, 'subscription_renew_confirmation_message', '<p>Please review the information below. If they are correct, please click on Process Button to renew your subscription for <strong>[PLAN_TITLE].</strong></p>'),
(38, 'admin_renw_email_subject', 'New subscription renewal for [PLAN_TITLE]'),
(39, 'admin_renew_email_body', '<p>Dear Administrator</p>\r\n<p>User <strong>[FIRST_NAME] [LAST_NAME]</strong> just completed renew his subscription for <strong>[PLAN_TITLE] </strong>for <strong>[NUMBER_DAYS] </strong>days. The subscription detail is as follow:</p>\r\n<p>[SUBSCRIPTION_DETAIL]</p>\r\n<p>Regards,</p>\r\n<p>Company Name</p>'),
(40, 'user_renew_email_subject', 'Subscription for [PLAN_TITLE] plan confirmation'),
(41, 'user_renew_email_body', '<p>Dear <strong>[FIRST_NAME] [LAST_NAME]</strong></p>\r\n<p>Thank you for renewing your subscription for <strong>[PLAN_TITLE]</strong>. Your new subscription expire date is <strong>[END_DATE]. </strong>The subscription detail is as follow:</p>\r\n<p>[SUBSCRIPTION_DETAIL]</p>\r\n<p>Regards,</p>\r\n<p>Company Name</p>'),
(42, 'renew_thanks_message', '<p>Thanks for renewing your subscription for subscription <strong>[PLAN_TITLE]</strong>. Your new expire date is <strong>[END_DATE]. </strong>Your subscription detail is as follow:</p>\r\n<p>[SUBSCRIPTION_DETAIL]</p>\r\n<p>Regards,</p>\r\n<p>Company Name</p>'),
(43, 'subscription_upgrade_form_msg', '<p>Please enter information on the form below to process upgrade your subscription from <strong>[FROM_PLAN_TITLE]</strong> To <strong>[PLAN_TITLE]</strong></p>'),
(44, 'subscription_upgrade_confirmation_message', '<p>Please review the upgrade subscription information in the form below. If they are correct, please click on <strong>Process</strong> button to process upgrade your subscription from <strong>[PLAN_TITLE]</strong> to <strong>[TO_PLAN_TITLE]</strong>.</p>'),
(45, 'admin_upgrade_email_subject', 'New subscription upgrade from [PLAN_TITLE] to [TO_PLAN_TITLE]'),
(46, 'admin_upgrade_email_body', '<p>Dear Administrator</p>\r\n<p>User <strong>[FIRST_NAME] [LAST_NAME]</strong> has just upgrade his subscription from <strong>[PLAN_TITLE]</strong> to <strong>[TO_PLAN_TITLE]</strong>.</p>\r\n<p>Regards,</p>\r\n<p>Website administrator team</p>'),
(47, 'user_upgrade_email_subject', 'Subscription upgrade Confirmation'),
(48, 'user_upgrade_email_body', '<p>Dear <strong>[FIRST_NAME] [LAST_NAME]</strong></p>\r\n<p>You just completed upgrade your subscription from <strong>[PLAN_TITLE]</strong> to <strong>[TO_PLAN_TITLE]</strong>. The subscription for <strong>[PLAN_TITLE] </strong>is now expired and you are now an active subscriber of new subscription plan <strong>[TO_PLAN_TITLE]</strong>. </p>\r\n<p>Regards,</p>\r\n<p>Company Name</p>\r\n<p> </p>'),
(49, 'upgrade_thanks_message', '<p>Dear <strong>[FIRST_NAME] [LAST_NAME]</strong></p>\r\n<p>You have just completed upgrade your subscription from <strong>[PLAN_TITLE]</strong> to <strong>[TO_PLAN_TITLE]</strong>. Your subscription for <strong>[PLAN_TITLE]</strong> is now expired and you are now active subscriber of subscription plan <strong>[TO_PLAN_TITLE]</strong>. The subscription detail is as follow:</p>\r\n<p>[SUBSCRIPTION_DETAIL]</p>\r\n<p>Regards,</p>\r\n<p>Website administrator team</p>'),
(50, 'first_reminder_email_subject', 'Your subscription for plan [PLAN_TITLE] will be expired in [NUMBER_DAYS] days'),
(51, 'first_reminder_email_body', '<p>Dear <strong>[FIRST_NAME] [LAST_NAME]</strong></p>\r\n<p>Your subscription for plan <strong>[PLAN_TITLE]</strong> on our site will be expired on <strong>[EXPIRE_DATE]</strong> (which is in <strong>[NUMBER_DAYS]</strong> from now).</p>'),
(52, 'second_reminder_email_subject', 'Your subscription for plan [PLAN_TITLE] will be expired in [NUMBER_DAYS] days'),
(53, 'second_reminder_email_body', '<p>Dear <strong>[FIRST_NAME] [LAST_NAME]</strong></p>\r\n<p>Your subscription for plan <strong>[PLAN_TITLE]</strong> on our site will be expired on <strong>[EXPIRE_DATE]</strong> (which is in [NUMBER_DAYS] from now).</p>'),
(54, 'option', 'com_osmembership'),
(55, 'task', 'save');